openapi: "3.0.1"
info:
  title: "Team04EbayAPIGateway"
  version: "1.0"
servers:
- url: "https://ckszaimc23.execute-api.us-east-2.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "EBAYAPIDepolyment1"
paths:
  /ebay-search:
    requestBody:
      description: The string of key words sent to EBAY search
      required: true
      content:
        application/json:
          schema:
            type: string
    post:
      responses:
        '200':
          description: An array of objects with EBAY products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
        default:
        description: "Default response for POST /ebay-search"